Added Index Display
3d-diploma-project/tetrahedron-web pull request #32
Opened 2024-11-01 12:15 UTC by Max1mj

https://github.com/user-attachments/assets/dd98a379-777f-41cd-8c2a-3818a5f2aa1f
# Summary:
- Added `NodeDisplay` component
- Added `positions` display on `index` hover

2024-11-01 14:09 UTC, HappyMary16 requested changes

2024-11-01 14:09 UTC, HappyMary16 commented on .vs/3d-app-web/v17/DocumentLayout.json
> +{
looks like an autogenerated file. Do we really need it in our repo?

2024-11-01 14:34 UTC, HappyMary16 commented
It's great that indexes are displayed but it doesn't match our design. You can talk to Tetiana to update a design or update implementation

2024-11-07 19:41 UTC, HappyMary16 commented
I would really like to see some progress in this PR

2024-11-09 09:45 UTC, HappyMary16 commented on src/components/NodeDisplay.tsx
> +  const indexedPositions = useMemo(() => {
is it possible to check in unit tests that this indexedPositions has a correct value after element initialization?

2024-11-15 17:42 UTC, HappyMary16 approved these changes

2024-11-16 09:50 UTC, ut5tw approved these changes

2024-11-16 09:52 UTC, merged